import { type Incident, type Report, type RouteOption, type SOSRequest, type EmergencyResource, type DisasterAlert, type RescueTeam, type CitizenReport } from './types'

const now = new Date()

export const mockIncidents: Incident[] = [
  { id: 'inc-001', type: 'flooded_road', severity: 'critical', location: { lat: 22.7196, lng: 75.8577, address: 'Rajwada, Indore, MP' }, title: 'Severe Flooding on MG Road', description: 'Heavy waterlogging with water levels exceeding 3 feet. Multiple vehicles stranded.', imageUrl: '/api/placeholder/400/300', reportedAt: new Date(now.getTime() - 120000).toISOString(), reportedBy: 'Citizen Report', aiVerificationScore: 98, citizenConfirmations: 15, status: 'verified', suggestedAlternateRoute: 'Take AB Road bypass via Scheme 78' },
  { id: 'inc-002', type: 'pothole', severity: 'high', location: { lat: 22.7333, lng: 75.8654, address: 'Scheme 54, Indore' }, title: 'Large Pothole on Main Road', description: 'Deep pothole approximately 3ft wide on the right lane, causing vehicles to swerve dangerously.', imageUrl: '/api/placeholder/400/300', reportedAt: new Date(now.getTime() - 3600000).toISOString(), reportedBy: 'Community Report', aiVerificationScore: 92, citizenConfirmations: 8, status: 'assigned' },
  { id: 'inc-003', type: 'fallen_tree', severity: 'high', location: { lat: 22.7056, lng: 75.8492, address: 'Bhawarkua, Indore' }, title: 'Fallen Tree Blocking Road', description: 'Large banyan tree has fallen across the road after heavy winds. Complete blockage.', imageUrl: '/api/placeholder/400/300', reportedAt: new Date(now.getTime() - 7200000).toISOString(), reportedBy: 'Traffic Police', aiVerificationScore: 95, citizenConfirmations: 12, status: 'work_in_progress', suggestedAlternateRoute: 'Use Patel Nagar bypass' },
  { id: 'inc-004', type: 'traffic_congestion', severity: 'medium', location: { lat: 22.7286, lng: 75.8767, address: 'Vijay Nagar Square, Indore' }, title: 'Heavy Traffic at Vijay Nagar', description: 'Severe congestion due to construction work. Delays of 30+ minutes expected.', reportedAt: new Date(now.getTime() - 1800000).toISOString(), reportedBy: 'AI Detection', aiVerificationScore: 88, citizenConfirmations: 45, status: 'verified', suggestedAlternateRoute: 'Take Ring Road via Palasia' },
  { id: 'inc-005', type: 'construction', severity: 'medium', location: { lat: 22.7142, lng: 75.8433, address: 'AB Road, Indore' }, title: 'Road Construction - Single Lane', description: 'Ongoing road widening project. Single lane alternating traffic. Expect 15-min delays.', reportedAt: new Date(now.getTime() - 86400000).toISOString(), reportedBy: 'Municipal Corporation', aiVerificationScore: 85, citizenConfirmations: 20, status: 'verified', suggestedAlternateRoute: 'Use service road via Sector A' },
  { id: 'inc-006', type: 'fire', severity: 'critical', location: { lat: 22.7208, lng: 75.8611, address: 'Market Area, Indore' }, title: 'Fire in Commercial Building', description: 'Fire reported on second floor of a commercial complex. Fire tenders on the way.', imageUrl: '/api/placeholder/400/300', reportedAt: new Date(now.getTime() - 600000).toISOString(), reportedBy: 'Emergency Services', aiVerificationScore: 99, citizenConfirmations: 30, status: 'under_verification', suggestedAlternateRoute: 'Avoid entire market area. Use Ring Road.' },
  { id: 'inc-007', type: 'accident', severity: 'high', location: { lat: 22.7269, lng: 75.8695, address: 'MR-10 Road, Indore' }, title: 'Multi-Vehicle Collision', description: 'Chain collision involving 4 vehicles. Ambulance dispatched. Two lanes blocked.', imageUrl: '/api/placeholder/400/300', reportedAt: new Date(now.getTime() - 300000).toISOString(), reportedBy: 'Citizen Report', aiVerificationScore: 96, citizenConfirmations: 18, status: 'verified', suggestedAlternateRoute: 'Use parallel road via Saket Nagar' },
  { id: 'inc-008', type: 'waterlogging', severity: 'medium', location: { lat: 22.7109, lng: 75.8522, address: 'Palasia, Indore' }, title: 'Waterlogging on Palasia Road', description: 'Road shoulder waterlogged. One lane affected. Slow traffic advised.', reportedAt: new Date(now.getTime() - 5400000).toISOString(), reportedBy: 'Citizen Report', aiVerificationScore: 82, citizenConfirmations: 6, status: 'verified' },
  { id: 'inc-009', type: 'road_blockage', severity: 'critical', location: { lat: 22.7012, lng: 75.8345, address: 'NH-52, Near Dewas Naka' }, title: 'Building Collapse Blocking Highway', description: 'Under-construction building collapsed onto highway. All lanes blocked. Diversion in place.', imageUrl: '/api/placeholder/400/300', reportedAt: new Date(now.getTime() - 900000).toISOString(), reportedBy: 'Traffic Police', aiVerificationScore: 97, citizenConfirmations: 25, status: 'verified', suggestedAlternateRoute: 'Diversion via Dewas Road - Sector C' },
  { id: 'inc-010', type: 'landslide', severity: 'high', location: { lat: 22.5545, lng: 75.8245, address: 'Mhow Ghat, Indore' }, title: 'Landslide at Mhow Ghat Section', description: 'Small landslide after rainfall. One lane blocked. Debris clearance underway.', imageUrl: '/api/placeholder/400/300', reportedAt: new Date(now.getTime() - 14400000).toISOString(), reportedBy: 'Highway Authority', aiVerificationScore: 93, citizenConfirmations: 10, status: 'work_in_progress', suggestedAlternateRoute: 'Use alternative route via Pithampur' },
]

export const mockReports: Report[] = [
  { id: 'rpt-001', type: 'pothole', description: 'Multiple potholes on service road near Bombay Hospital', photoUrl: '/api/placeholder/400/300', location: { lat: 22.7345, lng: 75.8723, address: 'Bombay Hospital Road, Indore' }, reportedBy: 'Rahul Singh', reportedAt: new Date(now.getTime() - 7200000).toISOString(), aiCategory: 'pothole', aiSeverity: 'high', aiPriorityScore: 78, status: 'under_verification', citizenConfirmations: 3 },
  { id: 'rpt-002', type: 'broken_bridge', description: 'Small bridge over river has structural cracks visible after recent rains', photoUrl: '/api/placeholder/400/300', location: { lat: 22.6805, lng: 75.8102, address: 'Village Road, Near Indore' }, reportedBy: 'Gram Panchayat', reportedAt: new Date(now.getTime() - 172800000).toISOString(), aiCategory: 'broken_bridge', aiSeverity: 'critical', aiPriorityScore: 95, status: 'assigned', citizenConfirmations: 8 },
  { id: 'rpt-003', type: 'waterlogging', description: 'Drainage overflow causing waterlogging at bus stop', photoUrl: '/api/placeholder/400/300', location: { lat: 22.7412, lng: 75.8889, address: 'Sector C, Indore' }, reportedBy: 'Anita Verma', reportedAt: new Date(now.getTime() - 259200000).toISOString(), aiCategory: 'waterlogging', aiSeverity: 'medium', aiPriorityScore: 45, status: 'work_in_progress', citizenConfirmations: 12 },
]

export const mockRoutes: RouteOption[] = [
  { id: 'route-a', name: 'Route A - Via Ring Road', from: { lat: 22.7196, lng: 75.8577 }, to: { lat: 22.7333, lng: 75.8900 }, distance: '12.4 km', estimatedTime: '22 min', safetyScore: 94, hazards: [], isRecommended: true, color: 'green' },
  { id: 'route-b', name: 'Route B - Via MG Road', from: { lat: 22.7196, lng: 75.8577 }, to: { lat: 22.7333, lng: 75.8900 }, distance: '8.6 km', estimatedTime: '18 min', safetyScore: 72, hazards: ['Traffic congestion at Vijay Nagar', 'Waterlogging near Palasia'], isRecommended: false, color: 'yellow' },
  { id: 'route-c', name: 'Route C - Via AB Road', from: { lat: 22.7196, lng: 75.8577 }, to: { lat: 22.7333, lng: 75.8900 }, distance: '6.2 km', estimatedTime: '14 min', safetyScore: 38, hazards: ['Flooded road at Rajwada', 'Fallen tree at Bhawarkua', 'Pothole on AB Road'], isRecommended: false, color: 'red' },
]

export const mockSOSRequests: SOSRequest[] = [
  { id: 'sos-001', callerName: 'Priya Sharma', phoneNumber: '+91-9876543210', location: { lat: 22.7196, lng: 75.8577, address: 'Rajwada Area, Indore' }, message: 'Water entering ground floor. Need rescue for elderly parents.', medicalInfo: 'Father has diabetes, needs insulin', timestamp: new Date(now.getTime() - 300000).toISOString(), status: 'responding', priority: 'critical' },
  { id: 'sos-002', callerName: 'Amit Patel', phoneNumber: '+91-9988776655', location: { lat: 22.7056, lng: 75.8492, address: 'Bhawarkua, Indore' }, message: 'Tree fell on house. Family of 4 trapped inside.', timestamp: new Date(now.getTime() - 600000).toISOString(), status: 'responding', priority: 'critical' },
  { id: 'sos-003', callerName: 'Sunita Gupta', phoneNumber: '+91-8877665544', location: { lat: 22.7269, lng: 75.8695, address: 'MR-10 Road, Indore' }, message: 'Stranded in car due to flooding. Water rising. 2 children with me.', timestamp: new Date(now.getTime() - 1200000).toISOString(), status: 'pending', priority: 'high' },
]

export const mockEmergencyResources: EmergencyResource[] = [
  { id: 'er-001', type: 'shelter', name: 'Community Hall - Rajwada', location: { lat: 22.7185, lng: 75.8560, address: 'Rajwada, Indore' }, capacity: 500, currentOccupancy: 340, phone: '+91-731-1234567', status: 'available' },
  { id: 'er-002', type: 'hospital', name: 'Civil Hospital Indore', location: { lat: 22.7241, lng: 75.8715, address: 'Civil Hospital Rd, Indore' }, capacity: 800, currentOccupancy: 720, phone: '+91-731-2345678', status: 'limited' },
  { id: 'er-003', type: 'food_distribution', name: 'Relief Camp - Nehru Stadium', location: { lat: 22.7159, lng: 75.8632, address: 'Nehru Stadium, Indore' }, capacity: 2000, currentOccupancy: 1500, phone: '+91-731-3456789', status: 'available' },
  { id: 'er-004', type: 'water_point', name: 'Water Distribution - Tower Square', location: { lat: 22.7225, lng: 75.8680, address: 'Tower Square, Indore' }, capacity: 1000, currentOccupancy: 600, status: 'available' },
  { id: 'er-005', type: 'charging_station', name: 'Charging Hub - Bus Stand', location: { lat: 22.7201, lng: 75.8599, address: 'Indore Bus Stand' }, capacity: 100, currentOccupancy: 85, status: 'limited' },
  { id: 'er-006', type: 'medical_camp', name: 'Red Cross Medical Camp', location: { lat: 22.7173, lng: 75.8555, address: 'Rajwada Ground, Indore' }, capacity: 300, currentOccupancy: 180, phone: '+91-731-4567890', status: 'available' },
]

export const mockDisasterAlerts: DisasterAlert[] = [
  { id: 'da-001', type: 'flood', severity: 'critical', location: { lat: 22.7196, lng: 75.8577, address: 'Indore City, MP' }, title: 'Severe Flood Warning - Indore', description: 'Heavy rainfall causing widespread flooding in low-lying areas. Multiple rescues underway.', affectedPopulation: 25000, timestamp: new Date(now.getTime() - 600000).toISOString(), confidence: 94 },
  { id: 'da-002', type: 'flood', severity: 'high', location: { lat: 22.5180, lng: 75.7589, address: 'Dhar District, MP' }, title: 'Flood Alert - Dhar', description: 'River Narmada rising above danger level. Evacuation recommended in floodplain areas.', affectedPopulation: 12000, timestamp: new Date(now.getTime() - 3600000).toISOString(), confidence: 89 },
  { id: 'da-003', type: 'landslide', severity: 'medium', location: { lat: 22.5545, lng: 75.8245, address: 'Mhow Region, MP' }, title: 'Landslide Risk - Mhow Ghat', description: 'Soil saturation high. Potential landslides in hilly sections.', affectedPopulation: 4500, timestamp: new Date(now.getTime() - 7200000).toISOString(), confidence: 82 },
]

export const mockRescueTeams: RescueTeam[] = [
  { id: 'rt-001', name: 'NDRF Team Alpha', type: 'ndrf', location: { lat: 22.7185, lng: 75.8560, address: 'Rajwada, Indore' }, status: 'deployed', members: 45, eta: 'Arrived' },
  { id: 'rt-002', name: 'SDRF Indore Unit', type: 'sdrf', location: { lat: 22.7241, lng: 75.8715, address: 'Civil Hospital, Indore' }, status: 'deployed', members: 30, eta: 'Arrived' },
  { id: 'rt-003', name: 'Fire Brigade - Station 1', type: 'fire', location: { lat: 22.7208, lng: 75.8611, address: 'Market Area, Indore' }, status: 'deployed', members: 12, eta: 'Arrived' },
  { id: 'rt-004', name: 'Medical Response Unit', type: 'medical', location: { lat: 22.7173, lng: 75.8555, address: 'Rajwada Ground, Indore' }, status: 'deployed', members: 20, eta: 'Arrived' },
  { id: 'rt-005', name: 'NDRF Team Bravo', type: 'ndrf', location: { lat: 22.5180, lng: 75.7589, address: 'Dhar, MP' }, status: 'available', members: 40 },
]

export const mockCitizenReports: CitizenReport[] = [
  { id: 'cr-001', type: 'people_trapped', description: '3 elderly people trapped on first floor of building near Rajwada.', location: { lat: 22.7192, lng: 75.8570, address: 'Rajwada, Indore' }, reporterName: 'Vikram Singh', phoneNumber: '+91-9876123456', timestamp: new Date(now.getTime() - 480000).toISOString(), status: 'dispatched' },
  { id: 'cr-002', type: 'missing_person', description: 'My mother went missing during evacuation. 65 years old, blue saree.', location: { lat: 22.7170, lng: 75.8585, address: 'Near Rajwada Temple' }, reporterName: 'Neha Gupta', phoneNumber: '+91-8765432190', timestamp: new Date(now.getTime() - 1800000).toISOString(), status: 'received' },
  { id: 'cr-003', type: 'damaged_building', description: 'Building next to mine is partially collapsed.', location: { lat: 22.7210, lng: 75.8620, address: 'Market Area, Indore' }, reporterName: 'Rohit Kumar', phoneNumber: '+91-7654321098', timestamp: new Date(now.getTime() - 2400000).toISOString(), status: 'dispatched' },
]