import { type Incident, type Report, type RouteOption, type SOSRequest, type EmergencyResource, type DisasterAlert, type RescueTeam, type CitizenReport } from './types'

const now = new Date()

export const mockIncidents: Incident[] = [
  { id: 'inc-001', type: 'flooded_road', severity: 'critical', location: { lat: 21.2514, lng: 81.6296, address: 'GE Road, Raipur, CG' }, title: 'Severe Flooding on GE Road', description: 'Heavy waterlogging with water levels exceeding 3 feet. Multiple vehicles stranded.', imageUrl: '/api/placeholder/400/300', reportedAt: new Date(now.getTime() - 120000).toISOString(), reportedBy: 'Citizen Report', aiVerificationScore: 98, citizenConfirmations: 15, status: 'verified', suggestedAlternateRoute: 'Take Ring Road bypass via Tatibandh' },
  { id: 'inc-002', type: 'pothole', severity: 'high', location: { lat: 21.2614, lng: 81.6402, address: 'VIP Road, Raipur' }, title: 'Large Pothole on Main Road', description: 'Deep pothole approximately 3ft wide on the right lane, causing vehicles to swerve dangerously.', imageUrl: '/api/placeholder/400/300', reportedAt: new Date(now.getTime() - 3600000).toISOString(), reportedBy: 'Community Report', aiVerificationScore: 92, citizenConfirmations: 8, status: 'assigned' },
  { id: 'inc-003', type: 'fallen_tree', severity: 'high', location: { lat: 21.2402, lng: 81.6189, address: 'Pandri, Raipur' }, title: 'Fallen Tree Blocking Road', description: 'Large banyan tree has fallen across the road after heavy winds. Complete blockage.', imageUrl: '/api/placeholder/400/300', reportedAt: new Date(now.getTime() - 7200000).toISOString(), reportedBy: 'Traffic Police', aiVerificationScore: 95, citizenConfirmations: 12, status: 'work_in_progress', suggestedAlternateRoute: 'Use Shankar Nagar bypass' },
  { id: 'inc-004', type: 'traffic_congestion', severity: 'medium', location: { lat: 21.2589, lng: 81.6520, address: 'Telibandha Square, Raipur' }, title: 'Heavy Traffic at Telibandha', description: 'Severe congestion due to construction work. Delays of 30+ minutes expected.', reportedAt: new Date(now.getTime() - 1800000).toISOString(), reportedBy: 'AI Detection', aiVerificationScore: 88, citizenConfirmations: 45, status: 'verified', suggestedAlternateRoute: 'Take Ring Road via Mahamaya Temple' },
  { id: 'inc-005', type: 'construction', severity: 'medium', location: { lat: 21.2378, lng: 81.6220, address: 'Dhamtari Road, Raipur' }, title: 'Road Construction - Single Lane', description: 'Ongoing road widening project. Single lane alternating traffic. Expect 15-min delays.', reportedAt: new Date(now.getTime() - 86400000).toISOString(), reportedBy: 'Municipal Corporation', aiVerificationScore: 85, citizenConfirmations: 20, status: 'verified', suggestedAlternateRoute: 'Use service road via Sector 1' },
  { id: 'inc-006', type: 'fire', severity: 'critical', location: { lat: 21.2529, lng: 81.6320, address: 'Market Area, Raipur' }, title: 'Fire in Commercial Building', description: 'Fire reported on second floor of a commercial complex. Fire tenders on the way.', imageUrl: '/api/placeholder/400/300', reportedAt: new Date(now.getTime() - 600000).toISOString(), reportedBy: 'Emergency Services', aiVerificationScore: 99, citizenConfirmations: 30, status: 'under_verification', suggestedAlternateRoute: 'Avoid entire market area. Use Ring Road.' },
  { id: 'inc-007', type: 'accident', severity: 'high', location: { lat: 21.2560, lng: 81.6440, address: 'NH-30, Raipur' }, title: 'Multi-Vehicle Collision', description: 'Chain collision involving 4 vehicles. Ambulance dispatched. Two lanes blocked.', imageUrl: '/api/placeholder/400/300', reportedAt: new Date(now.getTime() - 300000).toISOString(), reportedBy: 'Citizen Report', aiVerificationScore: 96, citizenConfirmations: 18, status: 'verified', suggestedAlternateRoute: 'Use parallel road via Shankar Nagar' },
  { id: 'inc-008', type: 'waterlogging', severity: 'medium', location: { lat: 21.2550, lng: 81.6120, address: 'Mahamaya Temple Road, Raipur' }, title: 'Waterlogging near Mahamaya Temple', description: 'Road shoulder waterlogged. One lane affected. Slow traffic advised.', reportedAt: new Date(now.getTime() - 5400000).toISOString(), reportedBy: 'Citizen Report', aiVerificationScore: 82, citizenConfirmations: 6, status: 'verified' },
  { id: 'inc-009', type: 'road_blockage', severity: 'critical', location: { lat: 21.2450, lng: 81.6000, address: 'NH-53, Near Naya Raipur' }, title: 'Building Collapse Blocking Highway', description: 'Under-construction building collapsed onto highway. All lanes blocked. Diversion in place.', imageUrl: '/api/placeholder/400/300', reportedAt: new Date(now.getTime() - 900000).toISOString(), reportedBy: 'Traffic Police', aiVerificationScore: 97, citizenConfirmations: 25, status: 'verified', suggestedAlternateRoute: 'Diversion via Naya Raipur Road' },
  { id: 'inc-010', type: 'landslide', severity: 'high', location: { lat: 21.1500, lng: 81.5800, address: 'Khamtarai Ghat, Raipur' }, title: 'Landslide at Khamtarai Section', description: 'Small landslide after rainfall. One lane blocked. Debris clearance underway.', imageUrl: '/api/placeholder/400/300', reportedAt: new Date(now.getTime() - 14400000).toISOString(), reportedBy: 'Highway Authority', aiVerificationScore: 93, citizenConfirmations: 10, status: 'work_in_progress', suggestedAlternateRoute: 'Use alternative route via Arang' },
]

export const mockReports: Report[] = [
  { id: 'rpt-001', type: 'pothole', description: 'Multiple potholes on service road near Ram Mandir', photoUrl: '/api/placeholder/400/300', location: { lat: 21.2620, lng: 81.6350, address: 'Ram Mandir Road, Raipur' }, reportedBy: 'Rahul Singh', reportedAt: new Date(now.getTime() - 7200000).toISOString(), aiCategory: 'pothole', aiSeverity: 'high', aiPriorityScore: 78, status: 'under_verification', citizenConfirmations: 3 },
  { id: 'rpt-002', type: 'broken_bridge', description: 'Small bridge over Kharun river has structural cracks visible after recent rains', photoUrl: '/api/placeholder/400/300', location: { lat: 21.2100, lng: 81.6400, address: 'Kharun Bridge, Raipur' }, reportedBy: 'Gram Panchayat', reportedAt: new Date(now.getTime() - 172800000).toISOString(), aiCategory: 'broken_bridge', aiSeverity: 'critical', aiPriorityScore: 95, status: 'assigned', citizenConfirmations: 8 },
  { id: 'rpt-003', type: 'waterlogging', description: 'Drainage overflow causing waterlogging at bus stand', photoUrl: '/api/placeholder/400/300', location: { lat: 21.2565, lng: 81.6385, address: 'Raipur Bus Stand' }, reportedBy: 'Anita Verma', reportedAt: new Date(now.getTime() - 259200000).toISOString(), aiCategory: 'waterlogging', aiSeverity: 'medium', aiPriorityScore: 45, status: 'work_in_progress', citizenConfirmations: 12 },
]

export const mockRoutes: RouteOption[] = [
  { id: 'route-a', name: 'Route A - Via Ring Road', from: { lat: 21.2514, lng: 81.6296 }, to: { lat: 21.2680, lng: 81.6520 }, distance: '12.4 km', estimatedTime: '22 min', safetyScore: 94, hazards: [], isRecommended: true, color: 'green' },
  { id: 'route-b', name: 'Route B - Via VIP Road', from: { lat: 21.2514, lng: 81.6296 }, to: { lat: 21.2680, lng: 81.6520 }, distance: '8.6 km', estimatedTime: '18 min', safetyScore: 72, hazards: ['Traffic congestion at Telibandha', 'Waterlogging near Pandri'], isRecommended: false, color: 'yellow' },
  { id: 'route-c', name: 'Route C - Via GE Road', from: { lat: 21.2514, lng: 81.6296 }, to: { lat: 21.2680, lng: 81.6520 }, distance: '6.2 km', estimatedTime: '14 min', safetyScore: 38, hazards: ['Flooded road at GE Road', 'Fallen tree at Pandri', 'Pothole on Dhamtari Road'], isRecommended: false, color: 'red' },
]

export const mockSOSRequests: SOSRequest[] = [
  { id: 'sos-001', callerName: 'Priya Sharma', phoneNumber: '+91-9876543210', location: { lat: 21.2514, lng: 81.6296, address: 'GE Road, Raipur' }, message: 'Water entering ground floor. Need rescue for elderly parents.', medicalInfo: 'Father has diabetes, needs insulin', timestamp: new Date(now.getTime() - 300000).toISOString(), status: 'responding', priority: 'critical' },
  { id: 'sos-002', callerName: 'Amit Patel', phoneNumber: '+91-9988776655', location: { lat: 21.2402, lng: 81.6189, address: 'Pandri, Raipur' }, message: 'Tree fell on house. Family of 4 trapped inside.', timestamp: new Date(now.getTime() - 600000).toISOString(), status: 'responding', priority: 'critical' },
  { id: 'sos-003', callerName: 'Sunita Gupta', phoneNumber: '+91-8877665544', location: { lat: 21.2560, lng: 81.6440, address: 'NH-30, Raipur' }, message: 'Stranded in car due to flooding. Water rising. 2 children with me.', timestamp: new Date(now.getTime() - 1200000).toISOString(), status: 'pending', priority: 'high' },
]

export const mockEmergencyResources: EmergencyResource[] = [
  { id: 'er-001', type: 'shelter', name: 'Community Hall - Telibandha', location: { lat: 21.2589, lng: 81.6520, address: 'Telibandha, Raipur' }, capacity: 500, currentOccupancy: 320, phone: '+91-771-1234567', status: 'available' },
  { id: 'er-002', type: 'hospital', name: 'Dr. Bhimrao Ambedkar Hospital', location: { lat: 21.2565, lng: 81.6385, address: 'Civil Lines, Raipur' }, capacity: 800, currentOccupancy: 710, phone: '+91-771-2345678', status: 'limited' },
  { id: 'er-003', type: 'food_distribution', name: 'Relief Camp - Police Ground', location: { lat: 21.2540, lng: 81.6350, address: 'Police Ground, Raipur' }, capacity: 2000, currentOccupancy: 1400, phone: '+91-771-3456789', status: 'available' },
  { id: 'er-004', type: 'water_point', name: 'Water Distribution - Railway Station', location: { lat: 21.2530, lng: 81.6300, address: 'Raipur Railway Station' }, capacity: 1000, currentOccupancy: 580, status: 'available' },
  { id: 'er-005', type: 'charging_station', name: 'Charging Hub - Bus Stand', location: { lat: 21.2565, lng: 81.6385, address: 'Raipur Bus Stand' }, capacity: 100, currentOccupancy: 82, status: 'limited' },
  { id: 'er-006', type: 'medical_camp', name: 'Red Cross Medical Camp', location: { lat: 21.2550, lng: 81.6320, address: 'Jaistambh Chowk, Raipur' }, capacity: 300, currentOccupancy: 175, phone: '+91-771-4567890', status: 'available' },
]

export const mockDisasterAlerts: DisasterAlert[] = [
  { id: 'da-001', type: 'flood', severity: 'critical', location: { lat: 21.2514, lng: 81.6296, address: 'Raipur City, CG' }, title: 'Severe Flood Warning - Raipur', description: 'Heavy rainfall causing widespread flooding in low-lying areas. Multiple rescues underway.', affectedPopulation: 35000, timestamp: new Date(now.getTime() - 600000).toISOString(), confidence: 94 },
  { id: 'da-002', type: 'flood', severity: 'high', location: { lat: 21.1400, lng: 81.7800, address: 'Dhamtari District, CG' }, title: 'Flood Alert - Dhamtari', description: 'River Mahanadi rising above danger level. Evacuation recommended in floodplain areas.', affectedPopulation: 15000, timestamp: new Date(now.getTime() - 3600000).toISOString(), confidence: 89 },
  { id: 'da-003', type: 'landslide', severity: 'medium', location: { lat: 21.1500, lng: 81.5800, address: 'Khamtarai Region, CG' }, title: 'Landslide Risk - Khamtarai', description: 'Soil saturation high. Potential landslides in hilly sections.', affectedPopulation: 3500, timestamp: new Date(now.getTime() - 7200000).toISOString(), confidence: 82 },
]

export const mockRescueTeams: RescueTeam[] = [
  { id: 'rt-001', name: 'NDRF Team Alpha', type: 'ndrf', location: { lat: 21.2514, lng: 81.6296, address: 'GE Road, Raipur' }, status: 'deployed', members: 45, eta: 'Arrived' },
  { id: 'rt-002', name: 'SDRF Raipur Unit', type: 'sdrf', location: { lat: 21.2565, lng: 81.6385, address: 'Civil Lines, Raipur' }, status: 'deployed', members: 30, eta: 'Arrived' },
  { id: 'rt-003', name: 'Fire Brigade - Station 1', type: 'fire', location: { lat: 21.2529, lng: 81.6320, address: 'Market Area, Raipur' }, status: 'deployed', members: 15, eta: 'Arrived' },
  { id: 'rt-004', name: 'Medical Response Unit', type: 'medical', location: { lat: 21.2550, lng: 81.6320, address: 'Jaistambh Chowk, Raipur' }, status: 'deployed', members: 20, eta: 'Arrived' },
  { id: 'rt-005', name: 'NDRF Team Bravo', type: 'ndrf', location: { lat: 21.1400, lng: 81.7800, address: 'Dhamtari, CG' }, status: 'available', members: 40 },
]

export const mockCitizenReports: CitizenReport[] = [
  { id: 'cr-001', type: 'people_trapped', description: '3 elderly people trapped on first floor of building near Telibandha.', location: { lat: 21.2589, lng: 81.6520, address: 'Telibandha, Raipur' }, reporterName: 'Vikram Singh', phoneNumber: '+91-9876123456', timestamp: new Date(now.getTime() - 480000).toISOString(), status: 'dispatched' },
  { id: 'cr-002', type: 'missing_person', description: 'My mother went missing during evacuation. 65 years old, blue saree.', location: { lat: 21.2530, lng: 81.6300, address: 'Near Railway Station' }, reporterName: 'Neha Gupta', phoneNumber: '+91-8765432190', timestamp: new Date(now.getTime() - 1800000).toISOString(), status: 'received' },
  { id: 'cr-003', type: 'damaged_building', description: 'Building next to mine is partially collapsed.', location: { lat: 21.2529, lng: 81.6320, address: 'Market Area, Raipur' }, reporterName: 'Rohit Kumar', phoneNumber: '+91-7654321098', timestamp: new Date(now.getTime() - 2400000).toISOString(), status: 'dispatched' },
]